### ISSUE TITLE
hdmi问题

### ISSUE THREAD

**Issue by dsf1995cn** [zsyshuyang/Hackintosh-EFI-For-Deskmini-310-i5-9400-DW1560#1]
感谢分享，成功上车。开机使用中发现不能关闭显示器(通过hdmi连接)，否则显示器就连不上了，只能重启。请问有没有办法解决😂

**Comment by zsyshuyang** [comment]
建议用DP线。HDMI唤醒正常吗？

**Comment by SnailDove** [comment]
> 建议用DP线。HDMI唤醒正常吗？

我跟另外一个网友一起测试你的efi+黑果小兵的15.4 287 winpe+ uefi 版本，单独DP线正常，单独HDMI线唤醒开机屏幕不亮需要重新对屏幕开关机或者重新插拔HDMI线，暂时手头没有两根线

**Comment by zsyshuyang** [comment]
> > 建议用DP线。HDMI唤醒正常吗？
> 
> 我跟另外一个网友一起测试你的efi+黑果小兵的15.4 287 winpe+ uefi 版本，单独DP线正常，单独HDMI线唤醒屏幕不亮以及开机进度条加载完后屏幕黑掉（其他都正常）需要重新对屏幕开关机或者重新插拔HDMI线，暂时手头没有两根线，有机会待测双输出，感谢您的分享，持续关注。

谢谢测试反馈。HDMI是老大难问题，也试图去查询解决方法，比如EDID注入等，但效果寥寥，更换DP线后，一切问题都解决了。

**Comment by SnailDove** [comment]
> > > 建议用DP线。HDMI唤醒正常吗？
> > 
> > 
> > 我跟另外一个网友一起测试你的efi+黑果小兵的15.4 287 winpe+ uefi 版本，单独DP线正常，单独HDMI线唤醒屏幕不亮以及开机进度条加载完后屏幕黑掉（其他都正常）需要重新对屏幕开关机或者重新插拔HDMI线，暂时手头没有两根线，有机会待测双输出，感谢您的分享，持续关注。
> 
> 谢谢测试反馈。HDMI是老大难问题，也试图去查询解决方法，比如EDID注入等，但效果寥寥，更换DP线后，一切问题都解决了。

多谢大佬的分享！！

**Comment by SnailDove** [comment]
hdmi口睡醒开机修复方案如下，亲测可用：
http://bbs.pcbeta.com/viewthread-1850729-1-1.html

**Comment by SnailDove** [comment]
> > > 建议用DP线。HDMI唤醒正常吗？
> > 
> > 
> > 我跟另外一个网友一起测试你的efi+黑果小兵的15.4 287 winpe+ uefi 版本，单独DP线正常，单独HDMI线唤醒屏幕不亮以及开机进度条加载完后屏幕黑掉（其他都正常）需要重新对屏幕开关机或者重新插拔HDMI线，暂时手头没有两根线，有机会待测双输出，感谢您的分享，持续关注。
> 
> 谢谢测试反馈。HDMI是老大难问题，也试图去查询解决方法，比如EDID注入等，但效果寥寥，更换DP线后，一切问题都解决了。

hdmi口睡醒开机修复方案如下，亲测可用：
http://bbs.pcbeta.com/viewthread-1850729-1-1.html

**Comment by SnailDove** [comment]
> 感谢分享，成功上车。开机使用中发现不能关闭显示器(通过hdmi连接)，否则显示器就连不上了，只能重启。请问有没有办法解决😂

hdmi口睡醒开机修复方案如下，亲测可用：
http://bbs.pcbeta.com/viewthread-1850729-1-1.html

欢迎加入deskmini-h310机友群：
![](https://camo.githubusercontent.com/da32bb12efddacc607d03813114a923400986a94/687474703a2f2f71396b7672616663712e626b742e636c6f7564646e2e636f6d2f736e61696c646f76652e6769746875622e696f2f6465736b6d696e693331302f6465736b6d696e693331302d6861636b6572732545372542452541342545342542412538432545372542422542342545372541302538312e706e67)
