### ISSUE TITLE
带麦克风的蓝牙耳机

### ISSUE THREAD

**Issue by SnailDove** [zsyshuyang/Hackintosh-EFI-For-Deskmini-310-i5-9400-DW1560#2]
我想买一个带麦克风功能的蓝牙耳机，不知道你这个efi支持不，因为我手头上暂时没有带麦克风的蓝牙耳机。**各位有用过得，知我一声效果**，先谢谢大家了

**Comment by zsyshuyang** [comment]
测试过，带麦克风的蓝牙耳机可用。测试耳机：Beats Solo。打开设置-声音-输入，可以选择输入的设备。

**Comment by SnailDove** [comment]
> 测试过，带麦克风的蓝牙耳机可用。测试耳机：Beats Solo。打开设置-声音-输入，可以选择输入的设备。

我的网卡是 转接卡+BCM94360CS2（全新的非拆机卡），谢谢你的反馈

**Comment by zsyshuyang** [comment]
> > 测试过，带麦克风的蓝牙耳机可用。测试耳机：Beats Solo。打开设置-声音-输入，可以选择输入的设备。
> 
> 
> 
> 我的网卡是 转接卡+BCM94360CS2（全新的非拆机卡），谢谢你的反馈

此网卡免驱，应该是没有问题。加转接卡，塞的下？

**Comment by SnailDove** [comment]
> > > 测试过，带麦克风的蓝牙耳机可用。测试耳机：Beats Solo。打开设置-声音-输入，可以选择输入的设备。
> > 
> > 
> > 我的网卡是 转接卡+BCM94360CS2（全新的非拆机卡），谢谢你的反馈
> 
> 此网卡免驱，应该是没有问题。加转接卡，塞的下？

可以的 m2的螺丝不能旋得很紧

**Comment by SnailDove** [comment]
反馈+1 ：经测试，小米蓝牙真无线耳机 也可以使用
