### ISSUE TITLE
麦克风不正常

### ISSUE THREAD

**Issue by SnailDove** [zsyshuyang/Hackintosh-EFI-For-Deskmini-310-i5-9400-DW1560#4]
无法正常工作，上下两个3.5mm插口，都语音不了。

**Comment by zsyshuyang** [comment]
有线麦克风，下面那个口（mic和耳机二合一），上面那个口只是mic接口。Mac下插下面那个，Windows两边都可用。

**Comment by SnailDove** [comment]
> 有线麦克风，下面那个口（mic和耳机二合一），上面那个口只是mic接口。Mac下插下面那个，Windows两边都可用。

我这边，今天用你的efi都试了2个口都不能用，换一个efi可以了，可能哪里出问题？，黑果小兵15.4 287 winpe+镜像 + 你的efi

**Comment by zsyshuyang** [comment]
你需要打开声音设置，输入和输出可以选择具体设备




------------------ 原始邮件 ------------------
发件人: SnailDove <notifications@github.com&gt;
发送时间: 2020年4月30日 22:58
收件人: zsyshuyang/Hackintosh-EFI-For-Deskmini-310-i5-9400-DW1560 <Hackintosh-EFI-For-Deskmini-310-i5-9400-DW1560@noreply.github.com&gt;
抄送: zsyshuyang <zsyshuyang@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[zsyshuyang/Hackintosh-EFI-For-Deskmini-310-i5-9400-DW1560] 麦克风不正常 (#4)





  
有线麦克风，下面那个口（mic和耳机二合一），上面那个口只是mic接口。Mac下插下面那个，Windows两边都可用。
  
我这边，今天用你的efi都试了2个口都不能用，换一个efi可以了，可能哪里出问题？，黑果小兵15.4 287 winpe+镜像 + 你的efi

**Comment by zsyshuyang** [comment]
> > 有线麦克风，下面那个口（mic和耳机二合一），上面那个口只是mic接口。Mac下插下面那个，Windows两边都可用。
> 
> 
> 
> 我这边，今天用你的efi都试了2个口都不能用，换一个efi可以了，可能哪里出问题？，黑果小兵15.4 287 winpe+镜像 + 你的efi 

网卡不一样，你还需要删除几个内核驱动，以免冲突。具体如图：
![Uploading 80728305...]()

**Comment by zsyshuyang** [comment]
> > 有线麦克风，下面那个口（mic和耳机二合一），上面那个口只是mic接口。Mac下插下面那个，Windows两边都可用。
> 
> 
> 
> 我这边，今天用你的efi都试了2个口都不能用，换一个efi可以了，可能哪里出问题？，黑果小兵15.4 287 winpe+镜像 + 你的efi 

网卡不一样，你还需要删除几个内核驱动，以免冲突。具体如图：
![image](https://user-images.githubusercontent.com/6631046/80728620-ba1bc400-8b39-11ea-9c75-8d342ff1f490.jpeg)。

**Comment by SnailDove** [comment]
> 你需要打开声音设置，输入和输出可以选择具体设备
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: SnailDove <notifications@github.com&gt; 发送时间: 2020年4月30日 22:58 收件人: zsyshuyang/Hackintosh-EFI-For-Deskmini-310-i5-9400-DW1560 <Hackintosh-EFI-For-Deskmini-310-i5-9400-DW1560@noreply.github.com&gt; 抄送: zsyshuyang <zsyshuyang@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[zsyshuyang/Hackintosh-EFI-For-Deskmini-310-i5-9400-DW1560] 麦克风不正常 (#4) 有线麦克风，下面那个口（mic和耳机二合一），上面那个口只是mic接口。Mac下插下面那个，Windows两边都可用。 我这边，今天用你的efi都试了2个口都不能用，换一个efi可以了，可能哪里出问题？，黑果小兵15.4 287 winpe+镜像 + 你的efi — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

试过了不行，可能网卡不一样，我用另外一个github用户，他网卡跟我一样的，就可以了，感谢你这么详细帮我，点赞！！！ღ( ´･ᴗ･` )比心！！！！

**Comment by SnailDove** [comment]
> > > 有线麦克风，下面那个口（mic和耳机二合一），上面那个口只是mic接口。Mac下插下面那个，Windows两边都可用。
> > 
> > 
> > 我这边，今天用你的efi都试了2个口都不能用，换一个efi可以了，可能哪里出问题？，黑果小兵15.4 287 winpe+镜像 + 你的efi
> 
> 网卡不一样，你还需要删除几个内核驱动，以免冲突。具体如图：
> ![image](https://user-images.githubusercontent.com/6631046/80728620-ba1bc400-8b39-11ea-9c75-8d342ff1f490.jpeg)。

嗯嗯 赶忙试了一下，删掉以后macos确实可以用下面这个3.5mm接听说话。只不过，删掉以后，hdmi音频就输出不了。感谢你提供的方案！
